Expiration date update for group request pages
dropbox/merou pull request #401
Opened 2018-07-11 18:09 UTC by weifchen

Updating display of expiration date to be more aligned with way we represent other date fields.
- Updated template_util for date format handler
- Update the FE for displaying on group requests and individual group request action page

Tested:
- created user, request to join group
- logged in as admin, view group, view request pages, view individual request page, action
- Auto-expiry shows up when date is passed (log at the bottom of page)

2018-07-12 19:22 UTC, cbguder commented on grouper/fe/template_util.py
> +    if isinstance(date_obj, unicode) or isinstance(date_obj, basestring):
`unicode` is a subclass of `basestring`, so `isinstance(date_obj, basestring)` should be enough

2018-07-12 19:22 UTC, cbguder commented on grouper/fe/template_util.py
> +    if date_obj == '' or date_obj is None:
I think this check should happen somewhere else, probably `print_date`? Otherwise this method returns a datetime *or* a string.

2018-07-12 19:22 UTC, cbguder commented on grouper/fe/template_util.py
> +        date_obj = str(date_obj)
`strptime` can handle unicode, so no need to cast here

2018-07-12 19:22 UTC, cbguder commented on grouper/fe/template_util.py
> +        except:
Let's avoid a generic `except` here, and catch only what `strptime` raises, which I believe is `ValueError`.

2018-07-12 19:22 UTC, cbguder commented on grouper/fe/template_util.py
> +    if date_obj:
By the time we get here `date_obj` should never be None, so we can probably keep the assertion the same

2018-07-12 19:22 UTC, cbguder commented on grouper/fe/template_util.py
> -        # naive dates are assumed UTC
Let's keep this comment

2018-07-12 19:22 UTC, cbguder commented on grouper/fe/template_util.py
> +        return ""
This check would be unnecessary if `_make_date_obj` always returns a `datetime`.

2018-07-12 19:22 UTC, cbguder commented on grouper/fe/templates/group-request-update.html
> +                    {% if request.changes.expiration is defined %}
I think we always want the `<td>` to be there, even if there's no text in it. Also, can we add/update an itest for this?

2018-07-12 19:22 UTC, cbguder commented on grouper/fe/templates/group-requests.html
> +                        {% if request.changes.expiration == '' or request.changes.expiration is none or request.changes.expiration is not defined%}
Can we simplify this, maybe to something like `request.changes.get('expiration')` and let `print_date` handle the `None`?

2018-07-12 19:22 UTC, cbguder commented on grouper/models/group_edge.py
> -                    expiration = datetime.strptime(value, "%m/%d/%Y")
Let's not touch this logic in this diff.

2018-07-12 19:22 UTC, cbguder commented on requirements.txt
> +# MySQL-python==1.2.5
We probably don't want to commit this

2018-07-12 19:22 UTC, cbguder commented on grouper/models/request.py
> +
Accidental whitespace?

2019-03-29 19:17 UTC, karthik-shanmugam requested changes
Looks mostly good, couple small nits

2019-03-29 19:17 UTC, karthik-shanmugam commented on grouper/models/group_edge.py
> +                        assert expiration > _utcnow()
this assert looks pointless

2019-03-29 19:17 UTC, karthik-shanmugam commented on grouper/fe/template_util.py
> +        assert False, "{}>>>{}".format(input_date_obj, type(input_date_obj))
I would add some text to this message that makes is more descriptive, maybe something like "date {} is of unsupported type {}"

2019-03-29 19:17 UTC, karthik-shanmugam commented on grouper/fe/templates/group-requests.html
> +                        <td class="request-expiration">{{ request.changes.expiration|print_date }}</td>
nit: indentation

2019-03-29 19:17 UTC, karthik-shanmugam commented on grouper/models/group_edge.py
> +                    assert isinstance(expiration, datetime)
I don't think this assert is necessary; if `_make_date_obj` promises to always return a datetime we don't need to double check it.

2019-03-29 20:45 UTC, cbguder commented on grouper/models/group_edge.py
> +from grouper.fe.template_util import _make_date_obj, _utcnow
If we're using these methods here, let's move them elsewhere. Importing front-end code in a model is backwards.

2022-04-16 21:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dropbox/merou?pullRequest=401) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dropbox/merou?pullRequest=401) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dropbox/merou?pullRequest=401) it.</sub>

2023-04-18 20:11 UTC, closed without merging