Fixed minor html compliance issues found via SonarQube
dropbox/merou pull request #582
Opened 2019-09-28 23:04 UTC by TimYagan

Fixed minor html compliance issues found via SonarQube - Low Risk and improves browser compatibility

2019-09-30 20:47 UTC, rra requested changes
I'm dubious this will improve browser compatibility all that much, but agreed with low risk and happy to take the change anyway since it makes automated tools happier. (In reality much of this should be in style sheets instead, but that's a much larger change.)

There were just a few places where I noticed a few problems, and then I'm happy to merge this.

Thanks for your contribution!

2019-09-30 20:47 UTC, rra commented on grouper/fe/templates/email/base.html
> +    <<title></title>
Extra open `<` here, I think?

2019-09-30 20:47 UTC, rra commented on grouper/fe/templates/macros/ui.html
>      <i>
Need to change this one as well.

2019-09-30 20:47 UTC, rra commented on grouper/fe/templates/service.html
> +                        <i>preserve any pre-existing group membership (you don't want this)</em>
Also need to change the `<i>`.

2019-10-01 06:06 UTC, TimYagan commented
Thanks for the review. I wilö change that.

On Mon, 30 Sep 2019, 22:47 Russ Allbery, <notifications@github.com> wrote:

> *@rra* requested changes on this pull request.
>
> I'm dubious this will improve browser compatibility all that much, but
> agreed with low risk and happy to take the change anyway since it makes
> automated tools happier. (In reality much of this should be in style sheets
> instead, but that's a much larger change.)
>
> There were just a few places where I noticed a few problems, and then I'm
> happy to merge this.
>
> Thanks for your contribution!
> ------------------------------
>
> In grouper/fe/templates/email/base.html
> <https://github.com/dropbox/merou/pull/582#discussion_r329777829>:
>
> > @@ -2,6 +2,7 @@
>  <html>
>
>  <head>
> +    <<title></title>
>
> Extra open < here, I think?
> ------------------------------
>
> In grouper/fe/templates/macros/ui.html
> <https://github.com/dropbox/merou/pull/582#discussion_r329778139>:
>
> > @@ -303,18 +303,18 @@ <h3 class="panel-title">Service Accounts</h3>
>  {% macro account(user, type=None) -%}
>  {% if type == None %}
>  <a class="account-link" href="/{{ user.type | lower }}s/{{ user.name }}">
> -    <i class="fa fa-user{% if user.type.lower() == 'group' %}s{% endif %}"></i>
> +    <em class="fa fa-user{% if user.type.lower() == 'group' %}s{% endif %}"></em>
>      {% if user.role_user or user.is_service_account %}
>      <i>
>
> Need to change this one as well.
> ------------------------------
>
> In grouper/fe/templates/service.html
> <https://github.com/dropbox/merou/pull/582#discussion_r329778479>:
>
> > @@ -147,7 +147,7 @@ <h4 class="modal-title">Enable User</h4>
>                  <div class="modal-body">
>                      <p>Are you sure you want to enable this user?</p>
>                      <label class="checkbox normal-weight">
> -                        <i>preserve any pre-existing group membership (you don't want this)</i>
> +                        <i>preserve any pre-existing group membership (you don't want this)</em>
>
> Also need to change the <i>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dropbox/merou/pull/582?email_source=notifications&email_token=AHMKZKBPCIZCECDKHB5VGTLQMJQWVA5CNFSM4I3P6HL2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCGMQELY#pullrequestreview-295240239>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHMKZKHTJ745BCJIT3XX6D3QMJQWVANCNFSM4I3P6HLQ>
> .
>

2022-04-16 21:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dropbox/merou?pullRequest=582) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dropbox/merou?pullRequest=582) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dropbox/merou?pullRequest=582) it.</sub>

2023-04-18 20:11 UTC, closed without merging